services:
  web:
    # image: ubuntu/nginx
    build: .
    restart: always
    expose: 
      - "5000"
    env_file:
      - .env
    volumes:
      - ./persistentdata/templates:/app/app_dir/templates
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s